/*
 * ============================================================================
 * FILE: Product.java
 * PURPOSE: Data model representing a product listing in the UniTrade marketplace
 * LOCATION: app/src/main/java/com/example/unitrade/Product.java
 * 
 * DESCRIPTION:
 * The Product class is the core data model for all product listings in the
 * marketplace. It stores comprehensive information about items for sale,
 * including descriptions, pricing, images, and transaction history. Products
 * can have different statuses (SOLD, BOUGHT, DONATED) representing their
 * state in the marketplace lifecycle. The class implements Parcelable for
 * efficient inter-Activity data passing.
 * 
 * KEY FEATURES:
 * - Product details (name, price, description, condition)
 * - Multiple product images with URLs
 * - Category and location information
 * - Seller and buyer tracking
 * - Transaction status tracking
 * - Image version control (cache busting)
 * - Listing and transaction timestamps
 * - QR code for payment tracking
 * - Utility methods for filtering and searching
 * 
 * STATUS CONSTANTS:
 * - STATUS_BOUGHT = "BOUGHT"   : User purchased this product
 * - STATUS_SOLD = "SOLD"       : User sold this product
 * - STATUS_DONATED = "DONATED" : Product was donated
 * 
 * ============================================================================
 */

package com.example.unitrade;

// Import for Parcelable (Android object serialization)
import android.os.Parcel;
import android.os.Parcelable;

// Firebase timestamp support
import com.google.firebase.Timestamp;

// Java utilities
import java.util.ArrayList;                     // Dynamic list storage
import java.util.Date;                          // Java date objects
import java.util.List;                          // List interface

/**
 * ============================================================================
 * Class Declaration: Product
 * ============================================================================
 * 
 * Implements Parcelable - Allows efficient passing of Product objects
 * between Android Activities via Intent extras. More efficient than
 * Serializable for Android platform.
 */
public class Product implements Parcelable {

    // ========================================================================
    // SECTION 1: BASIC PRODUCT INFORMATION
    // ========================================================================
    
    // Unique identifier for this product listing
    // Auto-generated by Firebase when product is created
    private String productId;
    
    // Name/title of the product (e.g., "iPhone 13 Pro")
    // Displayed prominently in product listings
    private String productName;
    
    // Price in the seller's selected currency
    // Stored as double to support decimal values (e.g., 99.99)
    private double productPrice;
    
    // Detailed description of the product
    // Can include specifications, condition details, usage information
    private String productDescription;
    
    // Overall condition of product (e.g., "Like New", "Good", "Fair", "Poor")
    // Typically selected from predefined categories
    private String productCondition;
    
    // How long product has been used (in days)
    // Helps buyers assess wear and tear
    private int productUsedDaysTotal;
    
    // Current status of this product listing
    // Can be: STATUS_SOLD, STATUS_BOUGHT, STATUS_DONATED
    private String productStatus;
    
    // Alternative product condition field (may be "New" or "Used")
    private String productUsed;

    // ========================================================================
    // SECTION 2: PRODUCT CATEGORIZATION & LOCATION
    // ========================================================================
    
    // Category of product (e.g., "Electronics", "Books", "Furniture")
    // Used for filtering and organizing listings
    private String productCategory;
    
    // Location/city where product is located
    // Important for delivery and local pickup options
    private String location;

    // ========================================================================
    // SECTION 3: IMAGES & VISUAL DATA
    // ========================================================================
    
    // List of URLs pointing to product images in Firebase Cloud Storage
    // Usually contains 1-5 images showing different angles
    private List<String> imageUrls = new ArrayList<>();
    
    // Version/timestamp of images (for cache busting)
    // Incremented when images are updated, forces reload of new images
    private long imageVersion;

    // ========================================================================
    // SECTION 4: USER INFORMATION
    // ========================================================================
    
    // Firebase User ID of the person selling this product
    // Links product to seller so purchases can track seller
    private String sellerId;
    
    // Firebase User ID of the person who bought this product
    // Null if product hasn't been purchased yet
    private String buyerId;
    
    // Alternative field tracking who product was sold to
    private String soldTo;

    // ========================================================================
    // SECTION 5: TRANSACTION & STATUS INFORMATION
    // ========================================================================
    
    // Current status of this product in marketplace
    // Can be one of the STATUS_* constants (SOLD, BOUGHT, DONATED)
    private boolean buyTransaction;     // True if this is a purchase record
    private boolean sellTransaction;    // True if this is a sale record
    private boolean donation;           // True if product was donated
    
    // Stability score (possibly for recommendation algorithm)
    private int stability;
    
    // Timestamp of when transaction occurred
    private long transactionDate;
    
    // Timestamp of when product was created
    private long createdAt;
    
    // Date when product was listed (auto-set on creation)
    private Date listingDate;
    
    // Timestamp of when product was sold
    private Timestamp soldAt;
    
    // Reference ID to the Purchase document in Firestore
    // Links this product to its corresponding purchase record
    private String purchaseId;

    // ========================================================================
    // SECTION 6: UI & METADATA
    // ========================================================================
    
    // Flag for RecyclerView header display
    // Sometimes used to add section headers in product lists
    private boolean isHeader = false;
    
    // QR code URL for payment tracking
    // Can be scanned to verify/track payment for this product
    private String qrPaymentUrl;

    // ========================================================================
    // STATUS CONSTANTS
    // ========================================================================
    
    // Product was purchased by someone
    public static final String STATUS_BOUGHT = "BOUGHT";
    
    // Product was sold by this user
    public static final String STATUS_SOLD = "SOLD";
    
    // Product was donated
    public static final String STATUS_DONATED = "DONATED";

    // ========================================================================
    // CONSTRUCTORS
    // ========================================================================
    
    /**
     * REQUIRED EMPTY CONSTRUCTOR by Firebase
     * 
     * Firebase Firestore requires all model classes to have a no-argument
     * constructor for serialization/deserialization. All fields get
     * default values when called.
     */
    public Product() {
        // Empty constructor - required by Firebase
    }

    /**
     * FULL CONSTRUCTOR - Create product with all information
     * 
     * Used when creating new product listings with complete details.
     * 
     * @param id                Product unique identifier
     * @param name              Product name/title
     * @param price             Sale price
     * @param imageUrls         List of image URLs from Firebase Storage
     * @param description       Detailed product description
     * @param condition         Product condition (Like New, Good, etc.)
     * @param usedDaysTotal     Days product has been used
     * @param status            Current status (SOLD, BOUGHT, DONATED)
     * @param category          Product category
     * @param location          Physical location
     * @param sellerId          Firebase ID of seller
     * @param qrPaymentUrl      QR code for payment tracking
     * @param productUsed       Condition type (New/Used)
     */
    public Product(
            String id,
            String name,
            double price,
            List<String> imageUrls,
            String description,
            String condition,
            int usedDaysTotal,
            String status,
            String category,
            String location,
            String sellerId,
            String qrPaymentUrl,
            String productUsed
    ) {
        // Store all parameters directly
        this.productId = id;
        this.productName = name;
        this.productPrice = price;
        // Safe copy of image URLs (handles null)
        setImageUrls(imageUrls);
        this.productDescription = description;
        this.productCondition = condition;
        this.productUsedDaysTotal = usedDaysTotal;
        this.productStatus = status;
        this.productCategory = category;
        this.location = location;
        this.sellerId = sellerId;
        this.qrPaymentUrl = qrPaymentUrl;
        this.productUsed = productUsed;
        
        // Set image version to current time (for cache busting)
        this.imageVersion = System.currentTimeMillis();
        
        // Set listing date to now
        this.listingDate = new Date();
    }

    // ========================================================================
    // GETTERS - Basic Product Information
    // ========================================================================
    
    /**
     * Get product unique identifier
     * @return Firestore document ID
     */
    public String getId() {
        return productId;
    }

    /**
     * Get product name/title
     * @return Product name
     */
    public String getName() {
        return productName;
    }

    /**
     * Get product price
     * @return Sale price in seller's currency
     */
    public double getPrice() {
        return productPrice;
    }

    /**
     * Get product description
     * @return Full description text
     */
    public String getDescription() {
        return productDescription;
    }

    /**
     * Get product condition
     * @return Condition (Like New, Good, Fair, Poor)
     */
    public String getCondition() {
        return productCondition;
    }

    /**
     * Get how long product has been used
     * @return Days of usage
     */
    public int getUsedDaysTotal() {
        return productUsedDaysTotal;
    }

    /**
     * Get product status
     * @return Status (SOLD, BOUGHT, DONATED, etc.)
     */
    public String getStatus() {
        return productStatus;
    }

    /**
     * Get product category
     * @return Category name
     */
    public String getCategory() {
        return productCategory;
    }

    /**
     * Get product location
     * @return City/location
     */
    public String getLocation() {
        return location;
    }

    /**
     * Get product condition type (New vs Used)
     * @return Condition type
     */
    public String getProductUsed() {
        return productUsed;
    }

    // ========================================================================
    // GETTERS - Images & Cache Busting
    // ========================================================================
    
    /**
     * Get list of product image URLs
     * Returns a safe copy to prevent external modifications
     * @return List of Firebase Cloud Storage URLs
     */
    public List<String> getImageUrls() {
        // Return empty list if null, otherwise return copy
        return imageUrls == null ? new ArrayList<>() : new ArrayList<>(imageUrls);
    }

    /**
     * Get image version (for cache busting)
     * When image version changes, browser/Glide will reload images
     * @return Version timestamp
     */
    public long getImageVersion() {
        return imageVersion;
    }

    // ========================================================================
    // GETTERS - User & Transaction Information
    // ========================================================================
    
    /**
     * Get Firebase ID of product seller
     * @return Seller's user ID
     */
    public String getSellerId() {
        return sellerId;
    }

    /**
     * Get Firebase ID of product buyer
     * @return Buyer's user ID or null if not sold
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * Get user ID of who product was sold to
     * @return Buyer's user ID
     */
    public String getSoldTo() {
        return soldTo;
    }

    /**
     * Get purchase record ID in Firestore
     * Links to the Purchase document
     * @return Purchase document ID
     */
    public String getPurchaseId() {
        return purchaseId;
    }

    /**
     * Get timestamp of when product was sold
     * @return Firebase Timestamp
     */
    public Timestamp getSoldAt() {
        return soldAt;
    }

    // ========================================================================
    // GETTERS - Timestamps & Dates
    // ========================================================================
    
    /**
     * Get when product was created/uploaded
     * @return Timestamp in milliseconds
     */
    public long getCreatedAt() {
        return createdAt;
    }

    /**
     * Get when product was listed
     * Defaults to current time if null
     * @return Date object
     */
    public Date getListingDate() {
        if (listingDate == null)
            listingDate = new Date();  // Set to now if uninitialized
        return listingDate;
    }

    /**
     * Get transaction date
     * @return Transaction timestamp in milliseconds
     */
    public long getTransactionDate() {
        return transactionDate;
    }

    // ========================================================================
    // GETTERS - Transaction Flags
    // ========================================================================
    
    /**
     * Check if this product is a buy transaction
     * @return True if this is a purchase record
     */
    public boolean isBuyTransactionFlag() {
        return buyTransaction;
    }

    /**
     * Check if this product is a sell transaction
     * @return True if this is a sale record
     */
    public boolean isSellTransactionFlag() {
        return sellTransaction;
    }

    /**
     * Check if this product is a donation
     * @return True if product was donated
     */
    public boolean isDonationFlag() {
        return donation;
    }

    /**
     * Get stability score
     * @return Stability value (used for recommendation algorithm)
     */
    public int getStability() {
        return stability;
    }

    // ========================================================================
    // GETTERS - UI/Metadata
    // ========================================================================
    
    /**
     * Check if this is a header item (for RecyclerView section headers)
     * @return True if this is a UI header, false if actual product
     */
    public boolean isHeader() {
        return isHeader;
    }

    /**
     * Get QR code payment URL
     * @return QR code URL or null
     */
    public String getQrPaymentUrl() {
        return qrPaymentUrl;
    }

    // ========================================================================
    // SETTERS - Basic Product Information
    // ========================================================================
    
    /**
     * Set product unique identifier
     * @param id New product ID
     */
    public void setId(String id) {
        this.productId = id;
    }

    /**
     * Set product name/title
     * @param name New product name
     */
    public void setName(String name) {
        this.productName = name;
    }

    /**
     * Set product price
     * @param price New price
     */
    public void setPrice(double price) {
        this.productPrice = price;
    }

    /**
     * Set product description
     * @param description New description
     */
    public void setDescription(String description) {
        this.productDescription = description;
    }

    /**
     * Set product condition
     * @param condition New condition (Like New, Good, etc.)
     */
    public void setCondition(String condition) {
        this.productCondition = condition;
    }

    /**
     * Set product condition type
     * @param productUsed New condition type (New/Used)
     */
    public void setProductUsed(String productUsed) {
        this.productUsed = productUsed;
    }

    /**
     * Set how long product has been used
     * @param usedDaysTotal Days of usage
     */
    public void setUsedDaysTotal(int usedDaysTotal) {
        this.productUsedDaysTotal = usedDaysTotal;
    }

    /**
     * Set product status
     * @param status New status (SOLD, BOUGHT, DONATED)
     */
    public void setStatus(String status) {
        this.productStatus = status;
    }

    /**
     * Set product category
     * @param category New category
     */
    public void setCategory(String category) {
        this.productCategory = category;
    }

    /**
     * Set product location
     * @param location New location
     */
    public void setLocation(String location) {
        this.location = location;
    }

    // ========================================================================
    // SETTERS - Images & Cache Busting
    // ========================================================================
    
    /**
     * Set product image URLs
     * Creates safe copy to prevent external modifications
     * @param imageUrls New list of image URLs
     */
    public void setImageUrls(List<String> imageUrls) {
        // Null-safe copy: if null, use empty list
        this.imageUrls = imageUrls == null ? new ArrayList<>() : new ArrayList<>(imageUrls);
    }

    /**
     * Set image version (cache bust version)
     * Update this when images change to force reload
     * @param imageVersion New version timestamp
     */
    public void setImageVersion(long imageVersion) {
        this.imageVersion = imageVersion;
    }

    // ========================================================================
    // SETTERS - User & Transaction Information
    // ========================================================================
    
    /**
     * Set seller's Firebase ID
     * @param sellerId Seller's user ID
     */
    public void setSellerId(String sellerId) {
        this.sellerId = sellerId;
    }

    /**
     * Set buyer's Firebase ID
     * @param buyerId Buyer's user ID
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * Set who product was sold to
     * @param soldTo Buyer's user ID
     */
    public void setSoldTo(String soldTo) {
        this.soldTo = soldTo;
    }

    /**
     * Set purchase record reference
     * @param purchaseId Purchase document ID in Firestore
     */
    public void setPurchaseId(String purchaseId) {
        this.purchaseId = purchaseId;
    }

    /**
     * Set when product was sold
     * @param soldAt Firebase Timestamp
     */
    public void setSoldAt(Timestamp soldAt) {
        this.soldAt = soldAt;
    }

    // ========================================================================
    // SETTERS - Timestamps & Dates
    // ========================================================================
    
    /**
     * Set product listing date
     * @param listingDate Date product was listed
     */
    public void setListingDate(Date listingDate) {
        this.listingDate = listingDate;
    }

    /**
     * Set transaction date
     * @param transactionDate Transaction timestamp
     */
    public void setTransactionDate(long transactionDate) {
        this.transactionDate = transactionDate;
    }

    // ========================================================================
    // SETTERS - Transaction Flags
    // ========================================================================
    
    /**
     * Set if this is a buy transaction
     * @param buyTransaction True if purchase record
     */
    public void setBuyTransaction(boolean buyTransaction) {
        this.buyTransaction = buyTransaction;
    }

    /**
     * Set if this is a sell transaction
     * @param sellTransaction True if sale record
     */
    public void setSellTransaction(boolean sellTransaction) {
        this.sellTransaction = sellTransaction;
    }

    /**
     * Set if this product is a donation
     * @param donation True if donated
     */
    public void setDonation(boolean donation) {
        this.donation = donation;
    }

    /**
     * Set stability score
     * @param stability New stability value
     */
    public void setStability(int stability) {
        this.stability = stability;
    }

    // ========================================================================
    // SETTERS - UI/Metadata
    // ========================================================================
    
    /**
     * Set if this is a header item
     * @param header True if UI header
     */
    public void setHeader(boolean header) {
        isHeader = header;
    }

    /**
     * Set QR code payment URL
     * @param qrPaymentUrl QR code URL
     */
    public void setQrPaymentUrl(String qrPaymentUrl) {
        this.qrPaymentUrl = qrPaymentUrl;
    }

    // ========================================================================
    // PARCELABLE IMPLEMENTATION
    // ========================================================================
    
    /**
     * Constructor for deserialization from Parcel
     * Reconstructs Product from binary Parcel data when passed between Activities
     * @param in Parcel containing serialized Product
     */
    protected Product(Parcel in) {
        // Read strings (in same order as writeToParcel)
        productId = in.readString();           // Read product ID
        productName = in.readString();         // Read product name
        productPrice = in.readDouble();        // Read price
        imageUrls = in.createStringArrayList(); // Read image URLs list
        productDescription = in.readString(); // Read description
        productCondition = in.readString();   // Read condition
        productUsedDaysTotal = in.readInt(); // Read days used
        productStatus = in.readString();     // Read status
        productCategory = in.readString();   // Read category
        location = in.readString();          // Read location
        sellerId = in.readString();          // Read seller ID
        buyerId = in.readString();           // Read buyer ID
        
        // Read boolean as byte (0 or 1)
        isHeader = in.readByte() != 0;      // Read header flag
        
        // Read more strings
        qrPaymentUrl = in.readString();     // Read QR code URL
        
        // Read long value
        imageVersion = in.readLong();       // Read image version
        
        // Read listing date (stored as long timestamp)
        long time = in.readLong();
        listingDate = time == -1 ? null : new Date(time);  // Convert back to Date
        
        // Read transaction date
        transactionDate = in.readLong();    // Read transaction timestamp
        
        // Read transaction info
        soldTo = in.readString();           // Read sold to user ID
        long soldAtTime = in.readLong();
        soldAt = soldAtTime == -1 ? null : new Timestamp(new Date(soldAtTime)); // Convert to Timestamp
        purchaseId = in.readString();       // Read purchase ID
        
        // Read transaction flags
        buyTransaction = in.readByte() != 0;    // Read buy flag
        sellTransaction = in.readByte() != 0;   // Read sell flag
        donation = in.readByte() != 0;          // Read donation flag
        
        // Read stability
        stability = in.readInt();           // Read stability score
    }

    /**
     * Serialize Product to Parcel for passing between Activities
     * 
     * IMPORTANT: Write order must match constructor read order!
     * 
     * @param dest Parcel to write to
     * @param flags Parcelable flags (usually 0)
     */
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        // Write strings in consistent order
        dest.writeString(productId);         // Write product ID
        dest.writeString(productName);       // Write product name
        dest.writeDouble(productPrice);      // Write price
        dest.writeStringList(imageUrls);     // Write image URLs
        dest.writeString(productDescription); // Write description
        dest.writeString(productCondition);  // Write condition
        dest.writeInt(productUsedDaysTotal); // Write days used
        dest.writeString(productStatus);     // Write status
        dest.writeString(productCategory);   // Write category
        dest.writeString(location);          // Write location
        dest.writeString(sellerId);          // Write seller ID
        dest.writeString(buyerId);           // Write buyer ID
        
        // Write boolean as byte (1 for true, 0 for false)
        dest.writeByte((byte) (isHeader ? 1 : 0)); // Write header flag
        
        // Write more strings
        dest.writeString(qrPaymentUrl);      // Write QR code URL
        
        // Write long
        dest.writeLong(imageVersion);        // Write image version
        
        // Write listing date as long (timestamp)
        dest.writeLong(listingDate != null ? listingDate.getTime() : -1);
        
        // Write transaction date
        dest.writeLong(transactionDate);     // Write transaction timestamp
        
        // Write transaction info
        dest.writeString(soldTo);            // Write sold to user ID
        // Write Timestamp as long (represent as timestamp or -1 if null)
        dest.writeLong(soldAt != null ? soldAt.toDate().getTime() : -1);
        dest.writeString(purchaseId);        // Write purchase ID
        
        // Write transaction flags as bytes
        dest.writeByte((byte) (buyTransaction ? 1 : 0));  // Write buy flag
        dest.writeByte((byte) (sellTransaction ? 1 : 0)); // Write sell flag
        dest.writeByte((byte) (donation ? 1 : 0));        // Write donation flag
        
        // Write stability
        dest.writeInt(stability);            // Write stability score
    }

    /**
     * Required by Parcelable
     * Returns 0 for most cases (no special flags needed)
     */
    @Override
    public int describeContents() {
        return 0;  // No special parcelable objects
    }

    /**
     * REQUIRED CREATOR for Parcelable
     * This static object creates Product instances from Parcel data
     */
    public static final Creator<Product> CREATOR = new Creator<>() {
        
        /**
         * Create Product instance from Parcel
         * @param in Parcel containing Product data
         * @return New Product instance reconstructed from Parcel
         */
        @Override
        public Product createFromParcel(Parcel in) {
            return new Product(in);  // Call protected constructor
        }

        /**
         * Create array of Products for deserialization
         * @param size Size of array to create
         * @return New Product array
         */
        @Override
        public Product[] newArray(int size) {
            return new Product[size];  // Initialize empty array
        }
    };

    // ========================================================================
    // EQUALITY & HASHING
    // ========================================================================
    
    /**
     * Check if two Product objects are equal
     * Based on product ID comparison (two products are equal if same ID)
     * @param o Object to compare
     * @return True if products have same ID
     */
    @Override
    public boolean equals(Object o) {
        // If comparing to self, return true
        if (this == o)
            return true;
        
        // If not a Product instance, return false
        if (!(o instanceof Product))
            return false;
        
        // Cast to Product and compare IDs
        Product p = (Product) o;
        return productId != null && productId.equals(p.productId);
    }

    /**
     * Get hash code for Product
     * Used for storing in HashSet, HashMap, etc.
     * @return Hash code based on product ID
     */
    @Override
    public int hashCode() {
        // Return hash of ID or 0 if ID is null
        return productId == null ? 0 : productId.hashCode();
    }

    // ========================================================================
    // HELPER METHODS - Transaction Type Checking
    // ========================================================================
    
    /**
     * Check if this product was bought (status is BOUGHT)
     * @return True if product status equals STATUS_BOUGHT
     */
    public boolean isBuyTransaction() {
        return STATUS_BOUGHT.equals(productStatus);
    }

    /**
     * Check if this product was sold (status is SOLD)
     * @return True if product status equals STATUS_SOLD
     */
    public boolean isSellTransaction() {
        return STATUS_SOLD.equals(productStatus);
    }

    /**
     * Check if this product was donated (status is DONATED)
     * @return True if product status equals STATUS_DONATED
     */
    public boolean isDonation() {
        return STATUS_DONATED.equals(productStatus);
    }

    // ========================================================================
    // UTILITY METHODS - Filtering & Searching
    // ========================================================================
    
    /**
     * Filter products list by seller ID
     * 
     * Returns new list containing only products sold by specified seller.
     * Useful for displaying "all items from seller" views.
     * 
     * Example usage:
     * List<Product> sellerProducts = Product.filterBySeller(allProducts, "userId123");
     * 
     * @param allProducts List of all products to filter
     * @param sellerId Seller ID to filter by
     * @return New list containing only products from specified seller
     */
    public static List<Product> filterBySeller(List<Product> allProducts, String sellerId) {
        // Create empty result list
        List<Product> result = new ArrayList<>();
        
        // If either parameter is null, return empty list
        if (allProducts == null || sellerId == null)
            return result;
        
        // Loop through all products
        for (Product p : allProducts) {
            // If product's seller matches desired seller, add to result
            if (sellerId.equals(p.getSellerId()))
                result.add(p);
        }
        
        // Return filtered list
        return result;
    }

}  // End of Product class
